package entity;
// Generated 19-sep-2015 2:07:46 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Bodega generated by hbm2java
 */
@Entity
@Table(name="bodega"
    ,catalog="bdgasolinera"
)
public class Bodega  implements java.io.Serializable {


     private Integer idbodega;
     private String codigo;
     private String ubicacion;
     private Set productos = new HashSet(0);

    public Bodega() {
    }

	
    public Bodega(String codigo, String ubicacion) {
        this.codigo = codigo;
        this.ubicacion = ubicacion;
    }
    public Bodega(String codigo, String ubicacion, Set productos) {
       this.codigo = codigo;
       this.ubicacion = ubicacion;
       this.productos = productos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idbodega", unique=true, nullable=false)
    public Integer getIdbodega() {
        return this.idbodega;
    }
    
    public void setIdbodega(Integer idbodega) {
        this.idbodega = idbodega;
    }

    
    @Column(name="codigo", nullable=false, length=50)
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

    
    @Column(name="ubicacion", nullable=false, length=45)
    public String getUbicacion() {
        return this.ubicacion;
    }
    
    public void setUbicacion(String ubicacion) {
        this.ubicacion = ubicacion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="bodega")
    public Set getProductos() {
        return this.productos;
    }
    
    public void setProductos(Set productos) {
        this.productos = productos;
    }




}


