package entity;
// Generated 19-sep-2015 2:07:46 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Bomba generated by hbm2java
 */
@Entity
@Table(name="bomba"
    ,catalog="bdgasolinera"
)
public class Bomba  implements java.io.Serializable {


     private Integer idbomba;
     private Tanque tanque;
     private String nombre;
     private Set detallebombatcs = new HashSet(0);

    public Bomba() {
    }

	
    public Bomba(Tanque tanque, String nombre) {
        this.tanque = tanque;
        this.nombre = nombre;
    }
    public Bomba(Tanque tanque, String nombre, Set detallebombatcs) {
       this.tanque = tanque;
       this.nombre = nombre;
       this.detallebombatcs = detallebombatcs;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idbomba", unique=true, nullable=false)
    public Integer getIdbomba() {
        return this.idbomba;
    }
    
    public void setIdbomba(Integer idbomba) {
        this.idbomba = idbomba;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fktanque", nullable=false)
    public Tanque getTanque() {
        return this.tanque;
    }
    
    public void setTanque(Tanque tanque) {
        this.tanque = tanque;
    }

    
    @Column(name="nombre", nullable=false, length=50)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="bomba")
    public Set getDetallebombatcs() {
        return this.detallebombatcs;
    }
    
    public void setDetallebombatcs(Set detallebombatcs) {
        this.detallebombatcs = detallebombatcs;
    }




}


