package entity;
// Generated 19-sep-2015 2:07:46 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ccompra generated by hbm2java
 */
@Entity
@Table(name="ccompra"
    ,catalog="bdgasolinera"
)
public class Ccompra  implements java.io.Serializable {


     private Integer idccompra;
     private Ctgformapago ctgformapago;
     private Empleado empleado;
     private Proveedor proveedor;
     private Date fecha;
     private Set detalleccompras = new HashSet(0);

    public Ccompra() {
    }

	
    public Ccompra(Ctgformapago ctgformapago, Empleado empleado, Proveedor proveedor, Date fecha) {
        this.ctgformapago = ctgformapago;
        this.empleado = empleado;
        this.proveedor = proveedor;
        this.fecha = fecha;
    }
    public Ccompra(Ctgformapago ctgformapago, Empleado empleado, Proveedor proveedor, Date fecha, Set detalleccompras) {
       this.ctgformapago = ctgformapago;
       this.empleado = empleado;
       this.proveedor = proveedor;
       this.fecha = fecha;
       this.detalleccompras = detalleccompras;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idccompra", unique=true, nullable=false)
    public Integer getIdccompra() {
        return this.idccompra;
    }
    
    public void setIdccompra(Integer idccompra) {
        this.idccompra = idccompra;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fkctgFormaPago", nullable=false)
    public Ctgformapago getCtgformapago() {
        return this.ctgformapago;
    }
    
    public void setCtgformapago(Ctgformapago ctgformapago) {
        this.ctgformapago = ctgformapago;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fkempleado", nullable=false)
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fkproveedor", nullable=false)
    public Proveedor getProveedor() {
        return this.proveedor;
    }
    
    public void setProveedor(Proveedor proveedor) {
        this.proveedor = proveedor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha", nullable=false, length=10)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="ccompra")
    public Set getDetalleccompras() {
        return this.detalleccompras;
    }
    
    public void setDetalleccompras(Set detalleccompras) {
        this.detalleccompras = detalleccompras;
    }




}


