package entity;
// Generated 19-sep-2015 2:07:46 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Compra generated by hbm2java
 */
@Entity
@Table(name="compra"
    ,catalog="bdgasolinera"
)
public class Compra  implements java.io.Serializable {


     private Integer idcompra;
     private Ctgformapago ctgformapago;
     private Empleado empleado;
     private Proveedor proveedor;
     private Date fecha;
     private BigDecimal valorcompra;
     private Set detallecompras = new HashSet(0);

    public Compra() {
    }

	
    public Compra(Ctgformapago ctgformapago, Empleado empleado, Proveedor proveedor, Date fecha, BigDecimal valorcompra) {
        this.ctgformapago = ctgformapago;
        this.empleado = empleado;
        this.proveedor = proveedor;
        this.fecha = fecha;
        this.valorcompra = valorcompra;
    }
    public Compra(Ctgformapago ctgformapago, Empleado empleado, Proveedor proveedor, Date fecha, BigDecimal valorcompra, Set detallecompras) {
       this.ctgformapago = ctgformapago;
       this.empleado = empleado;
       this.proveedor = proveedor;
       this.fecha = fecha;
       this.valorcompra = valorcompra;
       this.detallecompras = detallecompras;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idcompra", unique=true, nullable=false)
    public Integer getIdcompra() {
        return this.idcompra;
    }
    
    public void setIdcompra(Integer idcompra) {
        this.idcompra = idcompra;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fkctgFormaPago", nullable=false)
    public Ctgformapago getCtgformapago() {
        return this.ctgformapago;
    }
    
    public void setCtgformapago(Ctgformapago ctgformapago) {
        this.ctgformapago = ctgformapago;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fkempleado", nullable=false)
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fkproveedor", nullable=false)
    public Proveedor getProveedor() {
        return this.proveedor;
    }
    
    public void setProveedor(Proveedor proveedor) {
        this.proveedor = proveedor;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha", nullable=false, length=10)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

    
    @Column(name="valorcompra", nullable=false, precision=12)
    public BigDecimal getValorcompra() {
        return this.valorcompra;
    }
    
    public void setValorcompra(BigDecimal valorcompra) {
        this.valorcompra = valorcompra;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="compra")
    public Set getDetallecompras() {
        return this.detallecompras;
    }
    
    public void setDetallecompras(Set detallecompras) {
        this.detallecompras = detallecompras;
    }




}


