package entity;
// Generated 19-sep-2015 2:07:46 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Ctgdepartamento generated by hbm2java
 */
@Entity
@Table(name="ctgdepartamento"
    ,catalog="bdgasolinera"
)
public class Ctgdepartamento  implements java.io.Serializable {


     private Integer idctgDepartamento;
     private String nombre;
     private Set ctgmunicipios = new HashSet(0);

    public Ctgdepartamento() {
    }

	
    public Ctgdepartamento(String nombre) {
        this.nombre = nombre;
    }
    public Ctgdepartamento(String nombre, Set ctgmunicipios) {
       this.nombre = nombre;
       this.ctgmunicipios = ctgmunicipios;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idctgDepartamento", unique=true, nullable=false)
    public Integer getIdctgDepartamento() {
        return this.idctgDepartamento;
    }
    
    public void setIdctgDepartamento(Integer idctgDepartamento) {
        this.idctgDepartamento = idctgDepartamento;
    }

    
    @Column(name="nombre", nullable=false, length=50)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="ctgdepartamento")
    public Set getCtgmunicipios() {
        return this.ctgmunicipios;
    }
    
    public void setCtgmunicipios(Set ctgmunicipios) {
        this.ctgmunicipios = ctgmunicipios;
    }




}


