package entity;
// Generated 19-sep-2015 2:07:46 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Ctgformapago generated by hbm2java
 */
@Entity
@Table(name="ctgformapago"
    ,catalog="bdgasolinera"
)
public class Ctgformapago  implements java.io.Serializable {


     private Integer idctgFormaPago;
     private String nombre;
     private String descripcion;
     private Set cventas = new HashSet(0);
     private Set compras = new HashSet(0);
     private Set ccompras = new HashSet(0);
     private Set ventas = new HashSet(0);

    public Ctgformapago() {
    }

	
    public Ctgformapago(String nombre) {
        this.nombre = nombre;
    }
    public Ctgformapago(String nombre, String descripcion, Set cventas, Set compras, Set ccompras, Set ventas) {
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.cventas = cventas;
       this.compras = compras;
       this.ccompras = ccompras;
       this.ventas = ventas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idctgFormaPago", unique=true, nullable=false)
    public Integer getIdctgFormaPago() {
        return this.idctgFormaPago;
    }
    
    public void setIdctgFormaPago(Integer idctgFormaPago) {
        this.idctgFormaPago = idctgFormaPago;
    }

    
    @Column(name="nombre", nullable=false, length=50)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="descripcion", length=50)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="ctgformapago")
    public Set getCventas() {
        return this.cventas;
    }
    
    public void setCventas(Set cventas) {
        this.cventas = cventas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="ctgformapago")
    public Set getCompras() {
        return this.compras;
    }
    
    public void setCompras(Set compras) {
        this.compras = compras;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="ctgformapago")
    public Set getCcompras() {
        return this.ccompras;
    }
    
    public void setCcompras(Set ccompras) {
        this.ccompras = ccompras;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="ctgformapago")
    public Set getVentas() {
        return this.ventas;
    }
    
    public void setVentas(Set ventas) {
        this.ventas = ventas;
    }




}


