package entity;
// Generated 19-sep-2015 2:07:46 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Ctgtipofactura generated by hbm2java
 */
@Entity
@Table(name="ctgtipofactura"
    ,catalog="bdgasolinera"
)
public class Ctgtipofactura  implements java.io.Serializable {


     private Integer idctgTipoFactura;
     private String nombre;
     private String descripcion;
     private Set ventas = new HashSet(0);

    public Ctgtipofactura() {
    }

	
    public Ctgtipofactura(String nombre) {
        this.nombre = nombre;
    }
    public Ctgtipofactura(String nombre, String descripcion, Set ventas) {
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.ventas = ventas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idctgTipoFactura", unique=true, nullable=false)
    public Integer getIdctgTipoFactura() {
        return this.idctgTipoFactura;
    }
    
    public void setIdctgTipoFactura(Integer idctgTipoFactura) {
        this.idctgTipoFactura = idctgTipoFactura;
    }

    
    @Column(name="nombre", nullable=false, length=50)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="descripcion", length=50)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="ctgtipofactura")
    public Set getVentas() {
        return this.ventas;
    }
    
    public void setVentas(Set ventas) {
        this.ventas = ventas;
    }




}


