package entity;
// Generated 19-sep-2015 2:07:46 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.faces.view.ViewScoped;//cuidar que la libreria a implementar sea estas 
import javax.inject.Named;//con estas son las adecuadas.
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Ctgtipoproducto generated by hbm2java
 */
@Entity
@Table(name="ctgtipoproducto"
    ,catalog="bdgasolinera"
)
@Named(value = "Tipoproducto")//para ser invocado desde la vista 
@ViewScoped//como se implementara
public class Ctgtipoproducto  implements java.io.Serializable {


     private Integer idctgTipoProducto;
     private String nombre;
     private String descripcion;
     private Set productos = new HashSet(0);

    public Ctgtipoproducto() {
    }

    public Ctgtipoproducto(String nombre, String descripcion) {
        this.nombre = nombre;
        this.descripcion = descripcion;
    }

	
    public Ctgtipoproducto(String nombre) {
        this.nombre = nombre;
    }
    public Ctgtipoproducto(String nombre, String descripcion, Set productos) {
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.productos = productos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idctgTipoProducto", unique=true, nullable=false)
    public Integer getIdctgTipoProducto() {
        return this.idctgTipoProducto;
    }
    
    public void setIdctgTipoProducto(Integer idctgTipoProducto) {
        this.idctgTipoProducto = idctgTipoProducto;
    }

    
    @Column(name="nombre", nullable=false, length=50)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="descripcion", length=50)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="ctgtipoproducto")
    public Set getProductos() {
        return this.productos;
    }
    
    public void setProductos(Set productos) {
        this.productos = productos;
    }




}


