package entity;
// Generated 19-sep-2015 2:07:46 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.faces.view.ViewScoped;
import javax.inject.Named;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Ctgtipodocumento generated by hbm2java
 */
@Entity
@Table(name="ctgtipodocumento"
    ,catalog="bdgasolinera"
)
@Named(value = "Tipodoc")//para ser invocado desde la vista 
@ViewScoped
public class Ctgtipodocumento  implements java.io.Serializable {


     private Integer idctgTipoDocumento;
     private String nombre;
     private String descripcio;
     private Set detalledocumentos = new HashSet(0);

    public Ctgtipodocumento() {
    }

	
    public Ctgtipodocumento(String nombre) {
        this.nombre = nombre;
    }
    public Ctgtipodocumento(String nombre, String descripcio, Set detalledocumentos) {
       this.nombre = nombre;
       this.descripcio = descripcio;
       this.detalledocumentos = detalledocumentos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idctgTipoDocumento", unique=true, nullable=false)
    public Integer getIdctgTipoDocumento() {
        return this.idctgTipoDocumento;
    }
    
    public void setIdctgTipoDocumento(Integer idctgTipoDocumento) {
        this.idctgTipoDocumento = idctgTipoDocumento;
    }

    
    @Column(name="nombre", nullable=false, length=50)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="descripcio", length=50)
    public String getDescripcio() {
        return this.descripcio;
    }
    
    public void setDescripcio(String descripcio) {
        this.descripcio = descripcio;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="ctgtipodocumento")
    public Set getDetalledocumentos() {
        return this.detalledocumentos;
    }
    
    public void setDetalledocumentos(Set detalledocumentos) {
        this.detalledocumentos = detalledocumentos;
    }




}


