package entity;
// Generated 19-sep-2015 2:07:46 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.faces.view.ViewScoped;
import javax.inject.Named;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Ctgtipocliente generated by hbm2java
 */
@Entity
@Table(name="ctgtipocliente"
    ,catalog="bdgasolinera"
)
@Named(value = "Tipocliente")//para ser invocado desde la vista 
@ViewScoped
public class Ctgtipocliente  implements java.io.Serializable {


     private Integer idctgTipoCliente;
     private String nombre;
     private String descripcion;
     private Set clientes = new HashSet(0);

    public Ctgtipocliente() {
    }

	
    public Ctgtipocliente(String nombre, String descripcion) {
        this.nombre = nombre;
        this.descripcion = descripcion;
    }
    public Ctgtipocliente(String nombre, String descripcion, Set clientes) {
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.clientes = clientes;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idctgTipoCliente", unique=true, nullable=false)
    public Integer getIdctgTipoCliente() {
        return this.idctgTipoCliente;
    }
    
    public void setIdctgTipoCliente(Integer idctgTipoCliente) {
        this.idctgTipoCliente = idctgTipoCliente;
    }

    
    @Column(name="nombre", nullable=false, length=50)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="descripcion", nullable=false, length=50)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="ctgtipocliente")
    public Set getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Set clientes) {
        this.clientes = clientes;
    }




}


