package entity;
// Generated 19-sep-2015 2:07:46 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Cventa generated by hbm2java
 */
@Entity
@Table(name="cventa"
    ,catalog="bdgasolinera"
)
public class Cventa  implements java.io.Serializable {


     private Integer idcventa;
     private Cliente cliente;
     private Ctgformapago ctgformapago;
     private Detallecaja detallecaja;
     private Empleado empleado;
     private Date fecha;
     private Set detalleventacs = new HashSet(0);

    public Cventa() {
    }

	
    public Cventa(Cliente cliente, Ctgformapago ctgformapago, Detallecaja detallecaja, Empleado empleado, Date fecha) {
        this.cliente = cliente;
        this.ctgformapago = ctgformapago;
        this.detallecaja = detallecaja;
        this.empleado = empleado;
        this.fecha = fecha;
    }
    public Cventa(Cliente cliente, Ctgformapago ctgformapago, Detallecaja detallecaja, Empleado empleado, Date fecha, Set detalleventacs) {
       this.cliente = cliente;
       this.ctgformapago = ctgformapago;
       this.detallecaja = detallecaja;
       this.empleado = empleado;
       this.fecha = fecha;
       this.detalleventacs = detalleventacs;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idcventa", unique=true, nullable=false)
    public Integer getIdcventa() {
        return this.idcventa;
    }
    
    public void setIdcventa(Integer idcventa) {
        this.idcventa = idcventa;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cliente_idcliente", nullable=false)
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fkctgFormaPago", nullable=false)
    public Ctgformapago getCtgformapago() {
        return this.ctgformapago;
    }
    
    public void setCtgformapago(Ctgformapago ctgformapago) {
        this.ctgformapago = ctgformapago;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fkdetalleCaja", nullable=false)
    public Detallecaja getDetallecaja() {
        return this.detallecaja;
    }
    
    public void setDetallecaja(Detallecaja detallecaja) {
        this.detallecaja = detallecaja;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fkempleado", nullable=false)
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha", nullable=false, length=10)
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cventa")
    public Set getDetalleventacs() {
        return this.detalleventacs;
    }
    
    public void setDetalleventacs(Set detalleventacs) {
        this.detalleventacs = detalleventacs;
    }




}


