package entity;
// Generated 19-sep-2015 2:07:46 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Detalleccompra generated by hbm2java
 */
@Entity
@Table(name="detalleccompra"
    ,catalog="bdgasolinera"
)
public class Detalleccompra  implements java.io.Serializable {


     private Integer iddetalleccompra;
     private Ccompra ccompra;
     private Tanque tanque;
     private BigDecimal precioCosto;
     private BigDecimal precioVenta;
     private BigDecimal cantidad;

    public Detalleccompra() {
    }

    public Detalleccompra(Ccompra ccompra, Tanque tanque, BigDecimal precioCosto, BigDecimal precioVenta, BigDecimal cantidad) {
       this.ccompra = ccompra;
       this.tanque = tanque;
       this.precioCosto = precioCosto;
       this.precioVenta = precioVenta;
       this.cantidad = cantidad;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="iddetalleccompra", unique=true, nullable=false)
    public Integer getIddetalleccompra() {
        return this.iddetalleccompra;
    }
    
    public void setIddetalleccompra(Integer iddetalleccompra) {
        this.iddetalleccompra = iddetalleccompra;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ccompra_idccompra", nullable=false)
    public Ccompra getCcompra() {
        return this.ccompra;
    }
    
    public void setCcompra(Ccompra ccompra) {
        this.ccompra = ccompra;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="tanque_idtanque", nullable=false)
    public Tanque getTanque() {
        return this.tanque;
    }
    
    public void setTanque(Tanque tanque) {
        this.tanque = tanque;
    }

    
    @Column(name="precio_costo", nullable=false, precision=12)
    public BigDecimal getPrecioCosto() {
        return this.precioCosto;
    }
    
    public void setPrecioCosto(BigDecimal precioCosto) {
        this.precioCosto = precioCosto;
    }

    
    @Column(name="precio_venta", nullable=false, precision=12)
    public BigDecimal getPrecioVenta() {
        return this.precioVenta;
    }
    
    public void setPrecioVenta(BigDecimal precioVenta) {
        this.precioVenta = precioVenta;
    }

    
    @Column(name="cantidad", nullable=false, precision=12)
    public BigDecimal getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(BigDecimal cantidad) {
        this.cantidad = cantidad;
    }




}


