package entity;
// Generated 19-sep-2015 2:07:46 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Detallecompra generated by hbm2java
 */
@Entity
@Table(name="detallecompra"
    ,catalog="bdgasolinera"
)
public class Detallecompra  implements java.io.Serializable {


     private Integer iddetallecompra;
     private Compra compra;
     private Producto producto;
     private BigDecimal cantidad;

    public Detallecompra() {
    }

    public Detallecompra(Compra compra, Producto producto, BigDecimal cantidad) {
       this.compra = compra;
       this.producto = producto;
       this.cantidad = cantidad;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="iddetallecompra", unique=true, nullable=false)
    public Integer getIddetallecompra() {
        return this.iddetallecompra;
    }
    
    public void setIddetallecompra(Integer iddetallecompra) {
        this.iddetallecompra = iddetallecompra;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fkcompra", nullable=false)
    public Compra getCompra() {
        return this.compra;
    }
    
    public void setCompra(Compra compra) {
        this.compra = compra;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fkproducto", nullable=false)
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }

    
    @Column(name="cantidad", nullable=false, precision=12)
    public BigDecimal getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(BigDecimal cantidad) {
        this.cantidad = cantidad;
    }




}


