package entity;
// Generated 19-sep-2015 2:07:46 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Detallecaja generated by hbm2java
 */
@Entity
@Table(name="detallecaja"
    ,catalog="bdgasolinera"
)
public class Detallecaja  implements java.io.Serializable {


     private Integer iddetalleCaja;
     private Empleado empleado;
     private String turno;
     private Set cventas = new HashSet(0);
     private Set ventas = new HashSet(0);

    public Detallecaja() {
    }

	
    public Detallecaja(Empleado empleado, String turno) {
        this.empleado = empleado;
        this.turno = turno;
    }
    public Detallecaja(Empleado empleado, String turno, Set cventas, Set ventas) {
       this.empleado = empleado;
       this.turno = turno;
       this.cventas = cventas;
       this.ventas = ventas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="iddetalleCaja", unique=true, nullable=false)
    public Integer getIddetalleCaja() {
        return this.iddetalleCaja;
    }
    
    public void setIddetalleCaja(Integer iddetalleCaja) {
        this.iddetalleCaja = iddetalleCaja;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fkempleado", nullable=false)
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }

    
    @Column(name="turno", nullable=false, length=25)
    public String getTurno() {
        return this.turno;
    }
    
    public void setTurno(String turno) {
        this.turno = turno;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="detallecaja")
    public Set getCventas() {
        return this.cventas;
    }
    
    public void setCventas(Set cventas) {
        this.cventas = cventas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="detallecaja")
    public Set getVentas() {
        return this.ventas;
    }
    
    public void setVentas(Set ventas) {
        this.ventas = ventas;
    }




}


