package entity;
// Generated 19-sep-2015 2:07:46 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Detalleventa generated by hbm2java
 */
@Entity
@Table(name="detalleventa"
    ,catalog="bdgasolinera"
)
public class Detalleventa  implements java.io.Serializable {


     private Integer iddetalleVenta;
     private Producto producto;
     private Venta venta;
     private int cantidad;
     private BigDecimal monto;
     private BigDecimal descuento;
     private BigDecimal subtotal;

    public Detalleventa() {
    }

	
    public Detalleventa(Producto producto, Venta venta, int cantidad, BigDecimal monto, BigDecimal subtotal) {
        this.producto = producto;
        this.venta = venta;
        this.cantidad = cantidad;
        this.monto = monto;
        this.subtotal = subtotal;
    }
    public Detalleventa(Producto producto, Venta venta, int cantidad, BigDecimal monto, BigDecimal descuento, BigDecimal subtotal) {
       this.producto = producto;
       this.venta = venta;
       this.cantidad = cantidad;
       this.monto = monto;
       this.descuento = descuento;
       this.subtotal = subtotal;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="iddetalleVenta", unique=true, nullable=false)
    public Integer getIddetalleVenta() {
        return this.iddetalleVenta;
    }
    
    public void setIddetalleVenta(Integer iddetalleVenta) {
        this.iddetalleVenta = iddetalleVenta;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fkproducto", nullable=false)
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fkventa", nullable=false)
    public Venta getVenta() {
        return this.venta;
    }
    
    public void setVenta(Venta venta) {
        this.venta = venta;
    }

    
    @Column(name="cantidad", nullable=false)
    public int getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }

    
    @Column(name="monto", nullable=false, precision=12)
    public BigDecimal getMonto() {
        return this.monto;
    }
    
    public void setMonto(BigDecimal monto) {
        this.monto = monto;
    }

    
    @Column(name="descuento", precision=12)
    public BigDecimal getDescuento() {
        return this.descuento;
    }
    
    public void setDescuento(BigDecimal descuento) {
        this.descuento = descuento;
    }

    
    @Column(name="subtotal", nullable=false, precision=12)
    public BigDecimal getSubtotal() {
        return this.subtotal;
    }
    
    public void setSubtotal(BigDecimal subtotal) {
        this.subtotal = subtotal;
    }




}


