package entity;
// Generated 19-sep-2015 2:07:46 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Detalledocumento generated by hbm2java
 */
@Entity
@Table(name="detalledocumento"
    ,catalog="bdgasolinera"
)
public class Detalledocumento  implements java.io.Serializable {


     private int iddetalledocumento;
     private Ctgtipodocumento ctgtipodocumento;
     private Empleado empleado;
     private String numero;

    public Detalledocumento() {
    }

    public Detalledocumento(int iddetalledocumento, Ctgtipodocumento ctgtipodocumento, Empleado empleado, String numero) {
       this.iddetalledocumento = iddetalledocumento;
       this.ctgtipodocumento = ctgtipodocumento;
       this.empleado = empleado;
       this.numero = numero;
    }
   
     @Id 

    
    @Column(name="iddetalledocumento", unique=true, nullable=false)
    public int getIddetalledocumento() {
        return this.iddetalledocumento;
    }
    
    public void setIddetalledocumento(int iddetalledocumento) {
        this.iddetalledocumento = iddetalledocumento;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fkctgTipoDocumento", nullable=false)
    public Ctgtipodocumento getCtgtipodocumento() {
        return this.ctgtipodocumento;
    }
    
    public void setCtgtipodocumento(Ctgtipodocumento ctgtipodocumento) {
        this.ctgtipodocumento = ctgtipodocumento;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="kfempleado", nullable=false)
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }

    
    @Column(name="numero", nullable=false, length=50)
    public String getNumero() {
        return this.numero;
    }
    
    public void setNumero(String numero) {
        this.numero = numero;
    }




}


