package entity;
// Generated 19-sep-2015 2:07:46 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.faces.view.ViewScoped;
import javax.inject.Named;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Empleado generated by hbm2java
 */
@Entity
@Table(name="empleado"
    ,catalog="bdgasolinera"
)
@Named("Empleado")
@ViewScoped
public class Empleado  implements java.io.Serializable {


     private Integer idempleado;
     private Rol rol;
     private String primerNombre;
     private String segundoNombre;
     private String primerApellido;
     private String segundoApellido;
     private Date fechaNacimiento;
     private Date fechaContratacion;
     private String genero;
     private String estadoCivil;
     private String mail;
     private String password;
     private String telefonoFijo;
     private String telefonoMovil;
     private String direccion;
     private String estado;
     private Set productos = new HashSet(0);
     private Set detallecajas = new HashSet(0);
     private Set cventas = new HashSet(0);
     private Set detalledocumentos = new HashSet(0);
     private Set compras = new HashSet(0);
     private Set ventas = new HashSet(0);
     private Set ccompras = new HashSet(0);

    public Empleado() {
    }

	
    public Empleado(Rol rol, String primerNombre, String primerApellido, Date fechaNacimiento, Date fechaContratacion, String genero, String estadoCivil, String mail, String password, String telefonoFijo, String estado) {
        this.rol = rol;
        this.primerNombre = primerNombre;
        this.primerApellido = primerApellido;
        this.fechaNacimiento = fechaNacimiento;
        this.fechaContratacion = fechaContratacion;
        this.genero = genero;
        this.estadoCivil = estadoCivil;
        this.mail = mail;
        this.password = password;
        this.telefonoFijo = telefonoFijo;
        this.estado = estado;
    }
    public Empleado(Rol rol, String primerNombre, String segundoNombre, String primerApellido, String segundoApellido, Date fechaNacimiento, Date fechaContratacion, String genero, String estadoCivil, String mail, String password, String telefonoFijo, String telefonoMovil, String direccion, String estado, Set productos, Set detallecajas, Set cventas, Set detalledocumentos, Set compras, Set ventas, Set ccompras) {
       this.rol = rol;
       this.primerNombre = primerNombre;
       this.segundoNombre = segundoNombre;
       this.primerApellido = primerApellido;
       this.segundoApellido = segundoApellido;
       this.fechaNacimiento = fechaNacimiento;
       this.fechaContratacion = fechaContratacion;
       this.genero = genero;
       this.estadoCivil = estadoCivil;
       this.mail = mail;
       this.password = password;
       this.telefonoFijo = telefonoFijo;
       this.telefonoMovil = telefonoMovil;
       this.direccion = direccion;
       this.estado = estado;
       this.productos = productos;
       this.detallecajas = detallecajas;
       this.cventas = cventas;
       this.detalledocumentos = detalledocumentos;
       this.compras = compras;
       this.ventas = ventas;
       this.ccompras = ccompras;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idempleado", unique=true, nullable=false)
    public Integer getIdempleado() {
        return this.idempleado;
    }
    
    public void setIdempleado(Integer idempleado) {
        this.idempleado = idempleado;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="drol", nullable=false)
    public Rol getRol() {
        return this.rol;
    }
    
    public void setRol(Rol rol) {
        this.rol = rol;
    }

    
    @Column(name="primer_nombre", nullable=false, length=50)
    public String getPrimerNombre() {
        return this.primerNombre;
    }
    
    public void setPrimerNombre(String primerNombre) {
        this.primerNombre = primerNombre;
    }

    
    @Column(name="segundo_nombre", length=50)
    public String getSegundoNombre() {
        return this.segundoNombre;
    }
    
    public void setSegundoNombre(String segundoNombre) {
        this.segundoNombre = segundoNombre;
    }

    
    @Column(name="primer_apellido", nullable=false, length=50)
    public String getPrimerApellido() {
        return this.primerApellido;
    }
    
    public void setPrimerApellido(String primerApellido) {
        this.primerApellido = primerApellido;
    }

    
    @Column(name="segundo_apellido", length=50)
    public String getSegundoApellido() {
        return this.segundoApellido;
    }
    
    public void setSegundoApellido(String segundoApellido) {
        this.segundoApellido = segundoApellido;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha_nacimiento", nullable=false, length=10)
    public Date getFechaNacimiento() {
        return this.fechaNacimiento;
    }
    
    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha_contratacion", nullable=false, length=10)
    public Date getFechaContratacion() {
        return this.fechaContratacion;
    }
    
    public void setFechaContratacion(Date fechaContratacion) {
        this.fechaContratacion = fechaContratacion;
    }

    
    @Column(name="genero", nullable=false, length=1)
    public String getGenero() {
        return this.genero;
    }
    
    public void setGenero(String genero) {
        this.genero = genero;
    }

    
    @Column(name="estado_civil", nullable=false, length=50)
    public String getEstadoCivil() {
        return this.estadoCivil;
    }
    
    public void setEstadoCivil(String estadoCivil) {
        this.estadoCivil = estadoCivil;
    }

    
    @Column(name="mail", nullable=false, length=50)
    public String getMail() {
        return this.mail;
    }
    
    public void setMail(String mail) {
        this.mail = mail;
    }

    
    @Column(name="password", nullable=false, length=50)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="telefono_fijo", nullable=false, length=11)
    public String getTelefonoFijo() {
        return this.telefonoFijo;
    }
    
    public void setTelefonoFijo(String telefonoFijo) {
        this.telefonoFijo = telefonoFijo;
    }

    
    @Column(name="telefono_movil", length=11)
    public String getTelefonoMovil() {
        return this.telefonoMovil;
    }
    
    public void setTelefonoMovil(String telefonoMovil) {
        this.telefonoMovil = telefonoMovil;
    }

    
    @Column(name="direccion", length=150)
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    
    @Column(name="estado", nullable=false, length=1)
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empleado")
    public Set getProductos() {
        return this.productos;
    }
    
    public void setProductos(Set productos) {
        this.productos = productos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empleado")
    public Set getDetallecajas() {
        return this.detallecajas;
    }
    
    public void setDetallecajas(Set detallecajas) {
        this.detallecajas = detallecajas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empleado")
    public Set getCventas() {
        return this.cventas;
    }
    
    public void setCventas(Set cventas) {
        this.cventas = cventas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empleado")
    public Set getDetalledocumentos() {
        return this.detalledocumentos;
    }
    
    public void setDetalledocumentos(Set detalledocumentos) {
        this.detalledocumentos = detalledocumentos;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empleado")
    public Set getCompras() {
        return this.compras;
    }
    
    public void setCompras(Set compras) {
        this.compras = compras;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empleado")
    public Set getVentas() {
        return this.ventas;
    }
    
    public void setVentas(Set ventas) {
        this.ventas = ventas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empleado")
    public Set getCcompras() {
        return this.ccompras;
    }
    
    public void setCcompras(Set ccompras) {
        this.ccompras = ccompras;
    }




}


