package entity;
// Generated 19-sep-2015 2:07:46 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Producto generated by hbm2java
 */
@Entity
@Table(name="producto"
    ,catalog="bdgasolinera"
)
public class Producto  implements java.io.Serializable {


     private Integer idproducto;
     private Bodega bodega;
     private Ctgtipoproducto ctgtipoproducto;
     private Empleado empleado;
     private String codigo;
     private String nombre;
     private String descripcion;
     private int cantidadExistencia;
     private int cantidadMinima;
     private String estado;
     private BigDecimal precioVenta;
     private BigDecimal precioCosto;
     private Set detalleventas = new HashSet(0);
     private Set detallecompras = new HashSet(0);

    public Producto() {
    }

	
    public Producto(Bodega bodega, Ctgtipoproducto ctgtipoproducto, Empleado empleado, String codigo, String nombre, int cantidadExistencia, int cantidadMinima, String estado, BigDecimal precioVenta, BigDecimal precioCosto) {
        this.bodega = bodega;
        this.ctgtipoproducto = ctgtipoproducto;
        this.empleado = empleado;
        this.codigo = codigo;
        this.nombre = nombre;
        this.cantidadExistencia = cantidadExistencia;
        this.cantidadMinima = cantidadMinima;
        this.estado = estado;
        this.precioVenta = precioVenta;
        this.precioCosto = precioCosto;
    }
    public Producto(Bodega bodega, Ctgtipoproducto ctgtipoproducto, Empleado empleado, String codigo, String nombre, String descripcion, int cantidadExistencia, int cantidadMinima, String estado, BigDecimal precioVenta, BigDecimal precioCosto, Set detalleventas, Set detallecompras) {
       this.bodega = bodega;
       this.ctgtipoproducto = ctgtipoproducto;
       this.empleado = empleado;
       this.codigo = codigo;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.cantidadExistencia = cantidadExistencia;
       this.cantidadMinima = cantidadMinima;
       this.estado = estado;
       this.precioVenta = precioVenta;
       this.precioCosto = precioCosto;
       this.detalleventas = detalleventas;
       this.detallecompras = detallecompras;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idproducto", unique=true, nullable=false)
    public Integer getIdproducto() {
        return this.idproducto;
    }
    
    public void setIdproducto(Integer idproducto) {
        this.idproducto = idproducto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fkbodega", nullable=false)
    public Bodega getBodega() {
        return this.bodega;
    }
    
    public void setBodega(Bodega bodega) {
        this.bodega = bodega;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fkctgTipoProducto", nullable=false)
    public Ctgtipoproducto getCtgtipoproducto() {
        return this.ctgtipoproducto;
    }
    
    public void setCtgtipoproducto(Ctgtipoproducto ctgtipoproducto) {
        this.ctgtipoproducto = ctgtipoproducto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fkempleado", nullable=false)
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }

    
    @Column(name="codigo", nullable=false, length=45)
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

    
    @Column(name="nombre", nullable=false, length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="descripcion", length=45)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    
    @Column(name="cantidad_existencia", nullable=false)
    public int getCantidadExistencia() {
        return this.cantidadExistencia;
    }
    
    public void setCantidadExistencia(int cantidadExistencia) {
        this.cantidadExistencia = cantidadExistencia;
    }

    
    @Column(name="cantidad_minima", nullable=false)
    public int getCantidadMinima() {
        return this.cantidadMinima;
    }
    
    public void setCantidadMinima(int cantidadMinima) {
        this.cantidadMinima = cantidadMinima;
    }

    
    @Column(name="estado", nullable=false, length=1)
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }

    
    @Column(name="precio_venta", nullable=false, precision=12)
    public BigDecimal getPrecioVenta() {
        return this.precioVenta;
    }
    
    public void setPrecioVenta(BigDecimal precioVenta) {
        this.precioVenta = precioVenta;
    }

    
    @Column(name="precio_costo", nullable=false, precision=12)
    public BigDecimal getPrecioCosto() {
        return this.precioCosto;
    }
    
    public void setPrecioCosto(BigDecimal precioCosto) {
        this.precioCosto = precioCosto;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="producto")
    public Set getDetalleventas() {
        return this.detalleventas;
    }
    
    public void setDetalleventas(Set detalleventas) {
        this.detalleventas = detalleventas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="producto")
    public Set getDetallecompras() {
        return this.detallecompras;
    }
    
    public void setDetallecompras(Set detallecompras) {
        this.detallecompras = detallecompras;
    }




}


