package entity;
// Generated 19-sep-2015 2:07:46 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Proveedor generated by hbm2java
 */
@Entity
@Table(name="proveedor"
    ,catalog="bdgasolinera"
)
public class Proveedor  implements java.io.Serializable {


     private Integer idproveedor;
     private Ctgpaisproveedor ctgpaisproveedor;
     private String nombre;
     private String telefono;
     private String mail;
     private String direccion;
     private String codigo;
     private String estado;
     private Set compras = new HashSet(0);
     private Set ccompras = new HashSet(0);

    public Proveedor() {
    }

	
    public Proveedor(Ctgpaisproveedor ctgpaisproveedor, String nombre, String telefono, String mail, String direccion, String codigo, String estado) {
        this.ctgpaisproveedor = ctgpaisproveedor;
        this.nombre = nombre;
        this.telefono = telefono;
        this.mail = mail;
        this.direccion = direccion;
        this.codigo = codigo;
        this.estado = estado;
    }
    public Proveedor(Ctgpaisproveedor ctgpaisproveedor, String nombre, String telefono, String mail, String direccion, String codigo, String estado, Set compras, Set ccompras) {
       this.ctgpaisproveedor = ctgpaisproveedor;
       this.nombre = nombre;
       this.telefono = telefono;
       this.mail = mail;
       this.direccion = direccion;
       this.codigo = codigo;
       this.estado = estado;
       this.compras = compras;
       this.ccompras = ccompras;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idproveedor", unique=true, nullable=false)
    public Integer getIdproveedor() {
        return this.idproveedor;
    }
    
    public void setIdproveedor(Integer idproveedor) {
        this.idproveedor = idproveedor;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fkctgPaisProveedor", nullable=false)
    public Ctgpaisproveedor getCtgpaisproveedor() {
        return this.ctgpaisproveedor;
    }
    
    public void setCtgpaisproveedor(Ctgpaisproveedor ctgpaisproveedor) {
        this.ctgpaisproveedor = ctgpaisproveedor;
    }

    
    @Column(name="nombre", nullable=false, length=50)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="telefono", nullable=false, length=11)
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }

    
    @Column(name="mail", nullable=false, length=25)
    public String getMail() {
        return this.mail;
    }
    
    public void setMail(String mail) {
        this.mail = mail;
    }

    
    @Column(name="direccion", nullable=false, length=150)
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    
    @Column(name="codigo", nullable=false, length=50)
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

    
    @Column(name="estado", nullable=false, length=1)
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="proveedor")
    public Set getCompras() {
        return this.compras;
    }
    
    public void setCompras(Set compras) {
        this.compras = compras;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="proveedor")
    public Set getCcompras() {
        return this.ccompras;
    }
    
    public void setCcompras(Set ccompras) {
        this.ccompras = ccompras;
    }




}


