package entity;
// Generated 19-sep-2015 2:07:46 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tanque generated by hbm2java
 */
@Entity
@Table(name="tanque"
    ,catalog="bdgasolinera"
)
public class Tanque  implements java.io.Serializable {


     private Integer idtanque;
     private String nombre;
     private BigDecimal existencia;
     private BigDecimal existenciaMaxima;
     private Set bombas = new HashSet(0);
     private Set detalleccompras = new HashSet(0);

    public Tanque() {
    }

	
    public Tanque(String nombre, BigDecimal existencia, BigDecimal existenciaMaxima) {
        this.nombre = nombre;
        this.existencia = existencia;
        this.existenciaMaxima = existenciaMaxima;
    }
    public Tanque(String nombre, BigDecimal existencia, BigDecimal existenciaMaxima, Set bombas, Set detalleccompras) {
       this.nombre = nombre;
       this.existencia = existencia;
       this.existenciaMaxima = existenciaMaxima;
       this.bombas = bombas;
       this.detalleccompras = detalleccompras;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idtanque", unique=true, nullable=false)
    public Integer getIdtanque() {
        return this.idtanque;
    }
    
    public void setIdtanque(Integer idtanque) {
        this.idtanque = idtanque;
    }

    
    @Column(name="nombre", nullable=false, length=50)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="existencia", nullable=false, precision=12)
    public BigDecimal getExistencia() {
        return this.existencia;
    }
    
    public void setExistencia(BigDecimal existencia) {
        this.existencia = existencia;
    }

    
    @Column(name="existencia_maxima", nullable=false, precision=12)
    public BigDecimal getExistenciaMaxima() {
        return this.existenciaMaxima;
    }
    
    public void setExistenciaMaxima(BigDecimal existenciaMaxima) {
        this.existenciaMaxima = existenciaMaxima;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tanque")
    public Set getBombas() {
        return this.bombas;
    }
    
    public void setBombas(Set bombas) {
        this.bombas = bombas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tanque")
    public Set getDetalleccompras() {
        return this.detalleccompras;
    }
    
    public void setDetalleccompras(Set detalleccompras) {
        this.detalleccompras = detalleccompras;
    }




}


